services:
  - docker
  
env:
  - IMAGETAG="-t fastsurfer:gpu-beta -f ./Docker/Dockerfile"
  - IMAGETAG="-t fastsurfer:cpu-beta -f ./Docker/Dockerfile_CPU"
  - IMAGETAG="-t fastsurfer:segonly-gpu-beta -f ./Docker/Dockerfile_FastSurferCNN"
  - IMAGETAG="-t fastsurfer:segonly-cpu-beta -f ./Docker/Dockerfile_FastSurferCNN_CPU"
  - IMAGETAG="-t fastsurfer:surfonly-cpu-beta -f ./Docker/Dockerfile_reconsurf"
  
script:
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --rm=true $IMAGETAG .
