function freqs = get_frequencies

%{
Whenever I decide on canonical frequencies, I should call this. The first
one is my "broadband" and subsequent ones are canonical frequencies.
%}

freqs = [0.5 4;...
    4 8;...
    8 12;...
    12 30;...
    30 80;...
    80 250;...
    0.5 250;];

end