%Pyloc Configuration File
---
lead_types:
  D:
    name: Depth
    radius: 3
    spacing: 10
    max_y: 1
    selectable: True
  G:
    name: Grid
    radius: 3
    spacing: 20
    selectable: True
  S:
    name: Strip
    radius: 5
    spacing: 20
    selectable: True
  uD:
    name: microDepth
    radius: 0
    spacing: 10
    max_y: 1
    selectable: False
  uG:
    name: microGrid
    radius: 0
    spacing: 20
    selectable: False
  uS:
    name: microStrip
    radius: 0
    spacing: 20
    selectable: False
  uW:
    name: microWire
    radius: 0
    spacing: 10
    max_y: 1
    selectable: False

micros:
  " None":
    name: " None"
  AdTech_MM16C (10x):
    name: "AdTech_MM16C (10x)"
    type: uD
    spacing:
      - -0.5
      - 0.5
      - 1.5
      - 2.5
    numbering:
      - 3
      - 3
      - 2
      - 2
  AdTech_MM16D (8x):
    name: "AdTech_MM16D (8x)"
    type: uD
    spacing:
      - -0.5
      - 0.5
      - 1.5
      - 2.5
    numbering:
      - 2
      - 2
      - 2
      - 2
  PMT (16x):
    name: "PMT (16x)"
    type: uD
    spacing:
      - 0.36
      - 0.63
      - 1.36
      - 2.36
    numbering:
      - 4
      - 4
      - 4
      - 4
  Behnke_Fried (9x):
    name: "Behnke_Fried (9x)"
    type: uW
    spacing:
      - 0.0
    numbering:
      - 9



ct_threshold: 99.96

ct_max_color: 1
ct_min_color: .3
lead_max_color: 1
lead_min_color: .25


colormaps:
  ct: 'bone'
  selected: 'spring'
  default: 'spectral'

selection_iterations: 2

lead_display: >
  {lead.label}{contact.label} {contact.lead_location_str} {contact.center_str}

zero_index_lead: false
