version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      - git fetch --unshallow

python:
  install:
    - requirements: docs/requirements.txt
    - path: .
      extra_requirements:
        - doc
