name: Parallelization

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: build-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pip:
    uses: ./.github/workflows/test_template.yml
    with:
      runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      extra-depends: dask joblib ray protobuf<4.0.0 # More info here https://github.com/ray-project/ray/pull/25211
